version: '3.8'

services:
  # backend_django:
  #   build:
  #     context: ./backend_django
  #     dockerfile: Dockerfile
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./backend_django:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db

  front-end-react:
    build:
      context: ./front-end-react
      dockerfile: Dockerfile
    command: npm start -- --host 0.0.0.0
    volumes:
      - ./front-end-react:/app
      - /app/node_modules
    ports:
      - "8080:8080"

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: mydb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  postgres_data:
