# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='None'),
        ),
    ]
